version: "3.9"

services:
  worker-incoming:
    image: node:20-alpine
    deploy:
      replicas: ${WORKER_INCOMING_REPLICAS:-1}
    environment:
      NODE_ENV: production
      # Postgres
      DATABASE_URL: "postgres://postgres:Alice*321@postgres:5432"
      PGHOST: postgres
      PGPORT: "5432"
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: "Alice*321"
      PG_SCHEMA: ${TENANT}

      # RabbitMQ
      AMQP_URL: "amqp://guest:guest@rabbit:5672/"
      INCOMING_QUEUE: "${TENANT}.incoming"
      # MinIO
      MINIO_ENDPOINT: "https://bucket.dkdevs.com.br"
      MINIO_ACCESS_KEY: "F8fuZbb0aA2GG3SBxEAP"
      MINIO_SECRET_KEY: "rhMeg4DHPN0NagLg8TEEsnUUBj56Ki3eulIQFjuX"
      MINIO_BUCKET: "bucket"
      TELEGRAM_TOKEN: "8264496732:AAHNXxzWeLIfYk7nAPFWGVteQLRb9i5yGlc"
      WHATSAPP_TOKEN: "EAAJu9LjBChkBPPQzp1vAOdNioRhJR7ZByNpTnZCETMjo68BLca6GUwRZBurgtE1bRHyE5OrTQ0TZBlIUH8TZCZCK4x6ivc7sRLC85F0u1FpMOjkdHUIWWhsQ562UiFZCsUzyjkWsZCGD4ZCHO04MiI2lcpMPw50rLGSd2D73uXvZALgn603FLzm4HkYJJ4Y3ZADgQZDZD"
      CENTRIFUGO_HTTP_URL: "https://realtime.northgate.ninechat.com.br"
      CENTRIFUGO_API_KEY: "332166e7-9408-4dfb-8984-6c1f609888e1"
      TENANT_ID: ${TENANT}

    command: >
      sh -lc '
        set -euo pipefail;
        apk add --no-cache git ca-certificates && update-ca-certificates;
        cd /;
        rm -rf /app && git clone --depth=1 https://github.com/intalkconnect/hmgsuccess.git /app;
        cd /app;
        if [ -f package-lock.json ]; then
          npm ci --omit=dev;
        else
          npm install --omit=dev --no-audit --no-fund --legacy-peer-deps || true;
        fi;
        node worker-incoming.js
      '
    networks:
      - nginx-proxy-manager_default
      - public_network
    restart: unless-stopped

  worker-outcoming:
    image: node:20-alpine
    deploy:
      replicas: ${WORKER_OUTGOING_REPLICAS:-1}
    environment:
      NODE_ENV: production
      # SOCKET_URL: https://hmg.ninechat.com.br
      # REALTIME_EMIT_URL: https://hmg.ninechat.com.br
      API_VERSION: v23.0
      WHATSAPP_TOKEN: "EAAJu9LjBChkBPPQzp1vAOdNioRhJR7ZByNpTnZCETMjo68BLca6GUwRZBurgtE1bRHyE5OrTQ0TZBlIUH8TZCZCK4x6ivc7sRLC85F0u1FpMOjkdHUIWWhsQ562UiFZCsUzyjkWsZCGD4ZCHO04MiI2lcpMPw50rLGSd2D73uXvZALgn603FLzm4HkYJJ4Y3ZADgQZDZD"
      PHONE_NUMBER_ID: "744772558726331"
      WHATSAPP_BUSINESS_ACCOUNT_ID: "3031479917032694"
      TELEGRAM_TOKEN: "8264496732:AAHNXxzWeLIfYk7nAPFWGVteQLRb9i5yGlc"
      # Postgres
      DATABASE_URL: "postgres://postgres:Alice*321@postgres:5432"
      PGHOST: postgres
      PGPORT: "5432"
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: "Alice*321"
      PG_SCHEMA: ${TENANT}
      # Redis
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      # RabbitMQ
      AMQP_URL: "amqp://guest:guest@rabbit:5672/"
      OUTGOING_QUEUE: "${TENANT}.outgoing"
      RABBIT_PREFETCH: 20
      # MinIO
      MINIO_ENDPOINT: "https://bucket.dkdevs.com.br"
      MINIO_ACCESS_KEY: "F8fuZbb0aA2GG3SBxEAP"
      MINIO_SECRET_KEY: "rhMeg4DHPN0NagLg8TEEsnUUBj56Ki3eulIQFjuX"
      MINIO_BUCKET: "bucket"

    command: >
      sh -lc '
        set -euo pipefail;
        apk add --no-cache git ca-certificates ffmpeg && update-ca-certificates;
        cd /;
        rm -rf /app && git clone --depth=1 https://github.com/intalkconnect/hmgsuccess.git /app;
        cd /app;
        if [ -f package-lock.json ]; then
          npm ci --omit=dev;
        else
          npm install --omit=dev --no-audit --no-fund --legacy-peer-deps || true;
        fi;
        node worker-outgoing.js
      '

    networks:
      - nginx-proxy-manager_default
      - public_network
    restart: unless-stopped

  worker-campaign:
    image: node:20-alpine
    deploy:
      replicas: ${WORKER_CAMPAIGN_REPLICAS:-1}
    environment:
      NODE_ENV: production
      TENANT: ${TENANT}
      # Postgres
      DATABASE_URL: "postgres://postgres:Alice*321@postgres:5432"
      PGHOST: postgres
      PGPORT: "5432"
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: "Alice*321"
      PG_SCHEMA: ${TENANT}
      # Envio (WABA/Telegram)
      API_VERSION: v23.0
      WHATSAPP_TOKEN: "EAAJu9LjBChkBPPQzp1vAOdNioRhJR7ZByNpTnZCETMjo68BLca6GUwRZBurgtE1bRHyE5OrTQ0TZBlIUH8TZCZCK4x6ivc7sRLC85F0u1FpMOjkdHUIWWhsQ562UiFZCsUzyjkWsZCGD4ZCHO04MiI2lcpMPw50rLGSd2D73uXvZALgn603FLzm4HkYJJ4Y3ZADgQZDZD"
      PHONE_NUMBER_ID: "744772558726331"
      WHATSAPP_BUSINESS_ACCOUNT_ID: "3031479917032694"
      TELEGRAM_TOKEN: "SEU_BOT_TOKEN"
      # Tuning campanha
      CAMPAIGN_SCHED_DB_TICK_MS: "5000"
      CAMPAIGN_BATCH_SIZE: "200"
      CAMPAIGN_MAX_ATTEMPTS: "5"
      CAMPAIGN_SEND_DELAY_MS: "0"   # ex. 200 para ~5/s
    command: >
      sh -lc '
        set -euo pipefail;
        apk add --no-cache git ca-certificates ffmpeg && update-ca-certificates;
        cd /;
        rm -rf /app && git clone --depth=1 https://github.com/intalkconnect/hmgsuccess.git /app;
        cd /app;
        npm install --omit=dev --no-audit --no-fund || true;
        node worker-campaign.js
      '
    networks:
      - nginx-proxy-manager_default
      - public_network
    restart: unless-stopped


  worker-status:
    image: node:20-alpine
    deploy:
      replicas: ${WORKER_STATUS_REPLICAS:-1}
    environment:
      NODE_ENV: production

      PG_SCHEMA: ${TENANT}
      # Rabbit
      AMQP_URL: "amqp://guest:guest@rabbit:5672/"
      STATUS_QUEUE: "${TENANT}.status"
      STATUS_PREFETCH: "100"
      # Postgres
      DATABASE_URL: "postgres://postgres:Alice*321@postgres:5432"
      PGHOST: postgres
      PGPORT: "5432"
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: "Alice*321"
    command: >
      sh -lc '
        set -euo pipefail;
        apk add --no-cache git ca-certificates && update-ca-certificates;
        cd /;
        rm -rf /app && git clone --depth=1 https://github.com/intalkconnect/hmgsuccess.git /app;
        cd /app;
        npm install --omit=dev --no-audit --no-fund || true;
        node worker-status.js
      '
    networks:
      - nginx-proxy-manager_default
      - public_network
    restart: unless-stopped

networks:
  nginx-proxy-manager_default:
    external: true
    name: nginx-proxy-manager_default
  public_network:
    external: true
    name: public_network
